version: "3.1"

services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      - USER_UID=9030
      - USER_GID=9030
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=/var/run/postgresql
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=...
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__DOMAIN=gitea.scheme.org
      - GITEA__server__HTTP_PORT=9030
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__server__ROOT_URL=https://%(DOMAIN)s/
    restart: always
    volumes:
      - ./data:/data
      - ./backup:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/postgresql:/var/run/postgresql
    ports:
      - "127.0.0.1:9030:9030"
